services:
  uptime-kuma:
    build:
      context: ./kuma
      dockerfile: Dockerfile
    image: custom-uptime-kuma:latest
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    environment:
      KUMA_PASS: ${KUMA_PASS}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  status-updater:
    build:
      context: ./kuma_updater
      dockerfile: Dockerfile
    volumes:
      - config_storage:/app/host_vars
    env_file:
    - .env
    environment:
      KUMA_URL: http://uptime-kuma:3001
      KUMA_USER: admin    
    restart: unless-stopped

  miner-restarter:
    build:
      context: ./miner_restarter
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
    - .env
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: DEBUG
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  config_fetcher:
    build:
      context: ./config_fetcher
      dockerfile: Dockerfile
    volumes:
      - config_storage:/app/host_vars
    environment:
      SPREADSHEET_ID: ${SPREADSHEET_ID}
      ENCRYPTION_MASTER_KEY: ${ENCRYPTION_MASTER_KEY}
    restart: unless-stopped

volumes:
  config_storage:
